CREATE TABLE PessoaFisica(
	Codigo INT	NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(255) NOT NULL,
	Endereco VARCHAR (255) NOT NULL,
	Cidade VARCHAR (255) NOT NULL,
	Estado CHAR(2) NOT NULL,
	RG  VARCHAR (12) NULL,
	CPF VARCHAR(11) NULL,
	DataDeNascimento DATETIME NOT NULL,
	Telefone VARCHAR(20) NULL,
	Celular VARCHAR(20) NULL,
	Email VARCHAR(255) NULL,
	NomeDoPai VARCHAR(255) NULL,
	NomeDaMae VARCHAR(255) NULL,
	DataDeInclusao DATETIME NULL DEFAULT GETDATE()
	)
GO