CREATE DATABASE [Atividade 2021-09-21]

CREATE TABLE AreaConhecimento(
	AreaConhecimentoID INT NOT NULL IDENTITY(1,1),
	Descricao VARCHAR(256) NOT NULL,
	DataInsert DATETIME NULL DEFAULT GETDATE(),
	CONSTRAINT PK_AreaConhecimento PRIMARY KEY (AreaConhecimentoID)
)


CREATE TABLE InstituicaoBancaria(
	InstituicaoBancariaID INT NOT NULL IDENTITY(1,1),
	CodigoBanco INT NULL,
	Descricao VARCHAR(MAX) NOT NULL,
	SiteWWW VARCHAR (MAX) NULL,
	DataInsert DATETIME NULL DEFAULT GETDATE()
	CONSTRAINT PK_InstituicaoBancaria PRIMARY KEY (InstituicaoBancariaID)
)

CREATE TABLE Curso(
	CursoID INT NOT NULL IDENTITY(1,1),
	Descricao VARCHAR(MAX) NOT NULL,
	DataInsert DATETIME NULL DEFAULT GETDATE()
	CONSTRAINT PK_Curso PRIMARY KEY (CursoID)
)

CREATE TABLE Profissao(
		ProfissaoID INT NOT NULL IDENTITY(1,1),
		Descricao VARCHAR(MAX) NOT NULL,
		DataInsert DATETIME NULL DEFAULT GETDATE(),
		CONSTRAINT PK_Profissao PRIMARY KEY (ProfissaoID)
)

CREATE TABLE Pais(
		PaisID INT NOT NULL IDENTITY (1,1),
		Sigla VARCHAR(3) NOT NULL,
		CodigoIdioma VARCHAR(2) NOT NULL,
		Descricao VARCHAR(MAX) NOT NULL,
		DataInsert DATETIME NULL DEFAULT GETDATE(),
		CONSTRAINT PK_Pais PRIMARY KEY (PaisID)
)




